### ISSUE TITLE
Privacy Badger is not compatible with multiprocess Firefox (e10s)

### ISSUE THREAD

**Issue by cpeterso** [EFForg/privacybadgerfirefox-legacy#208]
Here is the Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1006330

If you have any questions about add-on support for multiprocess Firefox (e10s), just drop by the #e10s IRC channel on irc.mozilla.org. MDN also has a good introduction:

https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by rugk** [comment]
Any news here?
Just FYI there is a helpful blog post about the future of add-ons (including e10s and add-on signing): https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

**Comment by cooperq** [comment]
no news. needs to be worked on. there are other things that need to be worked on more.

**Comment by kinwolfqc** [comment]
Any news on this?  e10s is now enabled by default in FF49 and Privacy Badger isn't working with e10s yet.

**Comment by willsALMANJ** [comment]
What is your plan for the future of the Firefox SDK version of Privacy Badger? e10s support probably needs to be done by spring/summer of 2017 (just guessing when it might be turned on for everyone based on what I have seen from Mozilla), but since you already have a Chrome version it might better to put the effort into porting the Chrome extension to a Firefox WebExtension rather than updating the SDK version.

I tried running `web-ext lint` on the Chrome version and got the output below. I think it is all warnings that can be ignored except the messages about `incognito` and the permissions for `privacy` and `unlimitedStorage`. I'm not sure about `privacy` (could not find any mention of it in the WebExtensions documentation), but the chrome incompatibilities page on MDN states that Firefox does not support `incognito: split` or `unlimitedStorage`, so those would need to worked around.

```
Code                    Message                             Description                                                   File            Line   Column
MANIFEST_JSON_INVALID   "/incognito" should match pattern   See https://mzl.la/1ZOhoEN (MDN Docs) for more information.   manifest.json                
                        "^spanning$"                                                                                                                   
NOTICES:

Code                     Message                                    Description                                                                              File                                Line   Column
MANIFEST_UNUSED_UPDATE   The "update_url" property is not used by   The "update_url" is not used by Firefox in the root of a manifest; your add-on will be   manifest.json                                    
                         Firefox.                                   updated via the Add-ons site and not your "update_url". See: https://mzl.la/25zqk4O                                                       
KNOWN_LIBRARY            Known JS library detected                  JavaScript libraries are discouraged for simple add-ons, but are generally accepted.     lib/underscore-min.js                            
KNOWN_LIBRARY            Known JS library detected                  JavaScript libraries are discouraged for simple add-ons, but are generally accepted.     lib/jquery-ui/js/jquery-1.10.2.js                
WARNINGS:

Code                     Message                                       Description                                                                           File                                Line   Column
MANIFEST_PERMISSIONS     /permissions: Unknown permissions             See https://mzl.la/1R1n1t0 (MDN Docs) for more information.                           manifest.json                                    
                         "unlimitedStorage" at 7.                                                                                                                                                             
MANIFEST_PERMISSIONS     /permissions: Unknown permissions "privacy"   See https://mzl.la/1R1n1t0 (MDN Docs) for more information.                           manifest.json                                    
                         at 1.                                                                                                                                                                                
UNADVISED_LIBRARY        Unadvised 3rd-party JS library                Your add-on uses a JavaScript library we do not recommend. Read more:                 lib/jquery-ui/js/jquery-1.10.2.js                
                                                                       https://bit.ly/1TRIyZY                                                                                                                 
UNEXPECTED_GLOGAL_ARG    Unexpected global passed as an argument       Passing a global as an argument is not recommended. Please make this a var instead.   lib/compat.js                       30     17    
FLAGGED_FILE_EXTENSION   Flagged file extensions found                 Files were found that are either unnecessary or have been included unintentionally.   scripts/makezip.sh                               
                                                                       They should be removed.                                                                                                                
FLAGGED_FILE_EXTENSION   Flagged file extensions found                 Files were found that are either unnecessary or have been included unintentionally.   scripts/setup_travis.sh                          
                                                                       They should be removed.                                                                                                                
FLAGGED_FILE_EXTENSION   Flagged file extensions found                 Files were found that are either unnecessary or have been included unintentionally.   scripts/run-nightly.sh                           
                                                                       They should be removed.                                                                                                                
FLAGGED_FILE_EXTENSION   Flagged file extensions found                 Files were found that are either unnecessary or have been included unintentionally.   scripts/makecrx.sh                               
                                                                       They should be removed.                                                                                                                
TABS_GETSELECTED         "tabs.getSelected" is deprecated or           This API has been deprecated by Chrome and has not been implemented by Firefox.       src/popup.js                        96     5     
                         unimplemented                                                                                                                                                                        
TABS_GETSELECTED         "tabs.getSelected" is deprecated or           This API has been deprecated by Chrome and has not been implemented by Firefox.       src/popup.js                        521    3     
                         unimplemented                                                                                                                                                                        
TABS_GETALLINWINDOW      "tabs.getAllInWindow" is deprecated or        This API has been deprecated by Chrome and has not been implemented by Firefox.       src/options.js                      95     7     
                         unimplemented                                                                                                                                                                        
TABS_GETSELECTED         "tabs.getSelected" is deprecated or           This API has been deprecated by Chrome and has not been implemented by Firefox.       src/options.js                      418    3     
                         unimplemented                                                                                                                                                                        
FLAGGED_FILE_EXTENSION   Flagged file extensions found                 Files were found that are either unnecessary or have been included unintentionally.   tests/run_selenium_tests.sh                      
                                                                       They should be removed.                                                                                                                
FLAGGED_FILE_EXTENSION   Flagged file extensions found                 Files were found that are either unnecessary or have been included unintentionally.   scripts/justrun.sh                               
                                                                       They should be removed.                                                                   
```

**Comment by cooperq** [comment]
@willsALMANJ we are indeed working towards getting the chrome version of privacy badger compatible with web extensions. That work is being tracked here: https://github.com/EFForg/privacybadgerchrome/pull/845

I have already, in that branch, fixed the issues with incognito, privacy, and unlimitedStorage.  The plan is to get this version out as soon as we find a strategy to migrate the data from the jpm extension to the web extension, this will hopefully be in the next couple of months.

**Comment by maximus5959** [comment]
Glad this is being worked on.

**Comment by Mikaela** [comment]
> That work is being tracked here: EFForg/privacybadgerchrome#845

Does this still apply? That pull request seems to be merged and [Milestone
Web Extensions API](https://github.com/EFForg/privacybadgerchrome/milestone/10) closed.

I would be interested in the ETA for this arriving to Firefox enabling multi-process for me or at least following the development happening (if I understand anything of it).

* * * * *

![My loaded Firefox addons](https://cloud.githubusercontent.com/assets/831184/18606599/4886dbe2-7cbd-11e6-805c-a86a9b642364.png)

**Comment by mirh** [comment]
It may be as well we just lack the "[multiprocess](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK#Testing_with_shims_disabled)" permission then.

**Comment by willsALMANJ** [comment]
My understanding from reading the issues is that the Chrome extension is now compatible with WebExtensions. I think the hold up is that a data migration tool for upgrading from the old Firefox SDK version to the new WebExtension version has not been created. This was mentioned in a comment above and also in this comment: https://github.com/EFForg/privacybadgerchrome/pull/845#issuecomment-221138613 but I haven't found any follow up to it in other issues in either the Firefox or Chrome issue trackers. I don't think the WebExtension version will be pushed to Mozilla until this is taken care of.

If you really wanted to do (and didn't care about keeping your old data), you could try building and signing the WebExtension version yourself.

**Comment by cooperq** [comment]
@willsALMANJ is correct about the reason for the holdup on this. I am working on a data migration scheme now, I plan to have the web extensions version released as soon as thats done. Hopefully in the next 3-4 weeks.

**Comment by Mikaela** [comment]
If I understood correctly, that is also being worked on Firefox Addons mailing list.

![valinta_260](https://cloud.githubusercontent.com/assets/831184/18659111/213e3b1a-7f11-11e6-93d6-d17d7d3538af.png)

*[Source for Telegram users](https://telegram.me/mozillian/17634)*

**Comment by rugk** [comment]
For migrating the data from the old extension to the web extension you may use the new hybrid extensions supported of Firefox 51: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

Examples: https://github.com/rpl/webextensions-examples/tree/examples/hybrid-addons-native-messaging/embedded-webextension-native-messaging

**Comment by Mikaela** [comment]
Has anything happened with this issue? PrivacyBadger continues being the only addon keeping me from e10s Firefox and I think e10s would fix annoying freezing I have sometimes (even if I think I know the culprit) and it seems like no commit has referenced here and the IRC channel has been silent.

I am even thinking of temporarily replacing Privacy Badger with µBlock Origin even if I would be fine with not-tracking advertisers.

**Comment by willsALMANJ** [comment]
I'm not sure what the current status is, but I believe the relevant commits are here: https://github.com/EFForg/privacybadgerfirefox/commits/dataMigrate. As I said in my previous post on here, the Chrome version of Privacy Badger already works on Firefox (with e10s). The issue is providing a smooth upgrade that preserves user data.

**Comment by cooperq** [comment]
The very next version of Privacy Badger will be e10s compatible as we are switching to web extensions. Yay! as far as @willsALMANJ yes you are correct. Those commits are the ones providing a smooth data migration path for users. Everything is set! Watch out for the next version, hopefully in mid december.

**Comment by Hasshu** [comment]
> Watch out for the next version, hopefully in mid december.

December of what year?

**Comment by mirh** [comment]
Since like December 15.

**Comment by wshanks** [comment]
Yeah, this issue could be closed because the version on AMO is now compatible with multiprocess Firefox. However, I think this repo has been deprecated because PrivacyBadger now uses the Chrome version for both Chrome and Firefox.

**Comment by Hasshu** [comment]
@mirh You ain't no fun at all. :/

@willsALMANJ Indeed, looks like this place is all but abandoned.

**Comment by mirh** [comment]
It's not fun. That's when newer version has been released. Use it. 
They should remove/port this bug tracker.

**Comment by Hasshu** [comment]
> It's not fun.

Uh... Never mind.

> That's when newer version has been released. Use it.

Figures. Actually, I have it installed. I just wasn't sure whether it's the one with initial e10s support.

> They should remove/port this bug tracker.

This.

**Comment by cooperq** [comment]
Indeed the current version of privacy badger is compatible with E10S. Thanks.
