### ISSUE TITLE
Missing capability/feature to protect against current inadvertent privacy leakage

### ISSUE THREAD

**Issue by Mclaughlinux** [EFForg/privacybadgerfirefox-legacy#741]
Currently, there’s a missing capability to completely _Delete any of the trackers from “Filter Settings” List_, in order to enhance offline privacy of browsing history.

**Expanded:**
Inadvertently, PB “records” in a sense, the browsing history, leaving traces of domains visited in the form of a trackers list. This means that the history of their tracker permission decisions - _**and thus browsing history**_ - is recorded for posterity, and in plain sight of other users of the same computer.

In the interest of keeping the OFFLINE browsing history private for users who would wish it to remain so, PB ought to enable _Deletion of any of the trackers from the editing list_. While this may make PB somewhat less effective, this suggested capability (and decision) should be left to users.

**Comment by cooperq** [comment]
I support this.

**Comment by MaxMillion** [comment]
I support this too.

**Comment by cooperq** [comment]
Hi, we have now switched to https://github.com/eff.org/privacybadger as the codebase for both firefox and chrome as of the next version of privacy badger. This feature will be available in the next version of privacy badger.
