### ISSUE TITLE
Whitelist broken

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadgerfirefox-legacy#806]
Privacy Badger is still active on domains that I have whitelisted. I have restarted my browser but the problem persist.

Browser: Firefox ESR 45.3.0
Privacy Badger 1.8.1

**Comment by davidhedlund** [comment]
testabc

**Comment by davidhedlund** [comment]
[privatelabel:bookmark]

**Comment by davidhedlund** [comment]
defg

**Comment by davidhedlund** [comment]
label:reet

**Comment by davidhedlund** [comment]
+1

**Comment by davidhedlund** [comment]
+davidhedlund

**Comment by cooperq** [comment]
I am unable to reproduce this. How are you whitelisting the sites? Please give me step by step details on how to reproduce this, preferably with screenshots.

**Comment by davidhedlund** [comment]
[mylabel:question](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aquestion%22+in%3Acomments&type=Issues&ref=searchresults)
