### ISSUE TITLE
Privacy Badger for Firefox consuming 100% CPU

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerfirefox-legacy#810]
In my regular Firefox profile, I'm seeing a situation where Firefox is unresponsive and consuming 100% CPU.  Disabling Privacy Badger drops this to 15-20% CPU (which is still pretty bad, but Privacy Badger is clearly exacerbating whatever performance issue this profile is experiencing).

**Comment by pde** [comment]
I was able to reproduce this for one disable / reenable cycle with PB. But not two. Will try to catch my browser doing this again...

**Comment by cooperq** [comment]
Peter are you using the latest version of pb from AMO or EFF (just to make sure you aren't using a strange dev copy or something :smile: )

Could you run a cpu profile if this happens again to see if we can figure out what is happening?

**Comment by 6a68** [comment]
@pde Did you have any other addons installed? It's good to disable all other addons when debugging CPU problems.

If you're still seeing this issue, there's a Firefox debugging addon that lets you easily share performance data for cases like this. You can download the addon and learn about it [here](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler).

**Comment by w3333** [comment]
I'm seeing the same or a similar problem with privacy badger. When I open the filter settings, Firefox hogs the CPU. Closing the settings tab immediately resolves this. Can be reproduced anytime on my machine. There seem to be no issues during normal operation with PB.

**Comment by cooperq** [comment]
Hi, we have now switched to https://github.com/eff.org/privacybadger as the codebase for both firefox and chrome as of the next version of privacy badger. If you are still having this issue as of the next update please re post your issue there.

**Comment by mirh** [comment]
https://github.com/EFForg/privacybadger
Working link :*

Any comment on when it's rolling out?

**Comment by cooperq** [comment]
oops! Thanks for that. Should be rolling out on tuesday.
