### ISSUE TITLE
framasoft.org is blocked

### ISSUE THREAD

**Issue by SansPseudoFix** [EFForg/privacybadgerfirefox-legacy#815]
Hi,
I'm a member of Framasoft, a french non-profit organization who aims to promote free software, free culture and users privacy  (see [this presentation in english](https://wiki.framasoft.org/presentation_en)), and several of our services are broken because of Privacy Badger's rules: [degooglisons-internet.org](https://degooglisons-internet.org/), [Framadate](https://framadate.org/), [Framasphere](http://framasphere.org/) and so on, because ``framasoft.org`` is blocked.

We need it because framasoft.org provides a navigation bar for our many services, allowing users to jump from a service to another, see our terms of use and other legal stuff. And we have many reports of users.

Can you consider whitelisting framasoft.org?

Regards.

**Comment by cooperq** [comment]
I can add framasoft.org to our cookie block list which will then stop it from setting cookies but still allow it to load but to completely whitelist it let me suggest that you adopt our Do Not Track policy which can be found at https://www.eff.org/dnt-policy
