### ISSUE TITLE
Confirm service worker loads are being checked

### ISSUE THREAD

**Issue by jonathanKingston** [EFForg/privacybadgerfirefox-legacy#821]
I noticed when inspecting another issue that the method: `isBlockableRequest` receives a null window object when within a Twitter page: contentLocation.spec="https://twitter.com/push_service_worker.js";

This means that the third party requests are not being checked if they are blockable or not meaning they will always load.

I didn't have time to double check this is the case however it seems worth making a test for at least as the signs suggest it doesn't.

**Comment by cooperq** [comment]
Hi, we have now switched to https://github.com/eff.org/privacybadger as the codebase for both firefox and chrome as of the next version of privacy badger. If you are still having this issue as of the next update please re post your issue there.
