### ISSUE TITLE
Possible to console.log blocked requests?

### ISSUE THREAD

**Issue by unhammer** [EFForg/privacybadgerfirefox-legacy#823]
I've several times had Privacy Badger block things on pages I'm developing because I test from e.g. localhost and make server request, and each time it takes me quite a while to figure out why e.g. an xhr is giving status 0 and no error message, or a cdn script simply doesn't show up in the network requests. Is it possible to get Privacy Badger to console.log when it blocks something?

**Comment by cooperq** [comment]
Hi, we have now switched to https://github.com/eff.org/privacybadger as the codebase for both firefox and chrome as of the next version of privacy badger. If you are still having this issue as of the next update please re post your issue there.

**Comment by unhammer** [comment]
I suppose that was supposed to be https://github.com/efforg/privacybadger …
