### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by MaxMillion** [EFForg/privacybadgerfirefox-legacy#824]
- Ability to manually add (and remove) domains, ideally with wild-card support; e.g., *.google-analytics.com.
- Ability to set a default action for sites first encountered?; e.g., rather than default to Allow, an option to set default state to: Block domain, Block cookies, Allow.
- Ability to import/export.

Great work. Liking the extension.

**Comment by ghostwords** [comment]
Import/export should be in the next major release (Firefox and Chrome codebases are getting consolidated): https://github.com/EFForg/privacybadgerchrome/pull/982.

**Comment by cooperq** [comment]
Hi, we have now switched to https://github.com/eff.org/privacybadger as the codebase for both firefox and chrome as of the next version of privacy badger.The features you have requested will be available in the next release.

**Comment by noromanba** [comment]
@cooperq 
It's a slight typo; https://github.com/EFForg/privacybadger , isn't it?

**Comment by cooperq** [comment]
Correct, sorry about that!
